// Code generated by protoc-gen-go.
// source: convox_led.proto
// DO NOT EDIT!

/*
Package org_convox_lights is a generated protocol buffer package.

It is generated from these files:
	convox_led.proto

It has these top-level messages:
	ConvoxLightConfig
*/
package main

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ConvoxLightConfig_Color_ColorSpace int32

const (
	ConvoxLightConfig_Color_RGB ConvoxLightConfig_Color_ColorSpace = 1
	ConvoxLightConfig_Color_HSV ConvoxLightConfig_Color_ColorSpace = 2
)

var ConvoxLightConfig_Color_ColorSpace_name = map[int32]string{
	1: "RGB",
	2: "HSV",
}
var ConvoxLightConfig_Color_ColorSpace_value = map[string]int32{
	"RGB": 1,
	"HSV": 2,
}

func (x ConvoxLightConfig_Color_ColorSpace) Enum() *ConvoxLightConfig_Color_ColorSpace {
	p := new(ConvoxLightConfig_Color_ColorSpace)
	*p = x
	return p
}
func (x ConvoxLightConfig_Color_ColorSpace) String() string {
	return proto.EnumName(ConvoxLightConfig_Color_ColorSpace_name, int32(x))
}
func (x *ConvoxLightConfig_Color_ColorSpace) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ConvoxLightConfig_Color_ColorSpace_value, data, "ConvoxLightConfig_Color_ColorSpace")
	if err != nil {
		return err
	}
	*x = ConvoxLightConfig_Color_ColorSpace(value)
	return nil
}

// Next Id: 5
type ConvoxLightConfig struct {
	Color             []*ConvoxLightConfig_Color `protobuf:"bytes,1,rep,name=color" json:"color,omitempty"`
	Period            *float32                   `protobuf:"fixed32,2,opt,name=period" json:"period,omitempty"`
	TransitionSteps   *float32                   `protobuf:"fixed32,3,opt,name=transition_steps" json:"transition_steps,omitempty"`
	CircleCompression *float32                   `protobuf:"fixed32,4,opt,name=circle_compression" json:"circle_compression,omitempty"`
	XXX_unrecognized  []byte                     `json:"-"`
}

func (m *ConvoxLightConfig) Reset()         { *m = ConvoxLightConfig{} }
func (m *ConvoxLightConfig) String() string { return proto.CompactTextString(m) }
func (*ConvoxLightConfig) ProtoMessage()    {}

func (m *ConvoxLightConfig) GetColor() []*ConvoxLightConfig_Color {
	if m != nil {
		return m.Color
	}
	return nil
}

func (m *ConvoxLightConfig) GetPeriod() float32 {
	if m != nil && m.Period != nil {
		return *m.Period
	}
	return 0
}

func (m *ConvoxLightConfig) GetTransitionSteps() float32 {
	if m != nil && m.TransitionSteps != nil {
		return *m.TransitionSteps
	}
	return 0
}

func (m *ConvoxLightConfig) GetCircleCompression() float32 {
	if m != nil && m.CircleCompression != nil {
		return *m.CircleCompression
	}
	return 0
}

type ConvoxLightConfig_Color struct {
	ColorSpace       *ConvoxLightConfig_Color_ColorSpace `protobuf:"varint,1,opt,name=color_space,enum=org.convox.lights.ConvoxLightConfig_Color_ColorSpace,def=2" json:"color_space,omitempty"`
	Coordinates      []uint32                            `protobuf:"varint,2,rep,name=coordinates" json:"coordinates,omitempty"`
	XXX_unrecognized []byte                              `json:"-"`
}

func (m *ConvoxLightConfig_Color) Reset()         { *m = ConvoxLightConfig_Color{} }
func (m *ConvoxLightConfig_Color) String() string { return proto.CompactTextString(m) }
func (*ConvoxLightConfig_Color) ProtoMessage()    {}

const Default_ConvoxLightConfig_Color_ColorSpace ConvoxLightConfig_Color_ColorSpace = ConvoxLightConfig_Color_HSV

func (m *ConvoxLightConfig_Color) GetColorSpace() ConvoxLightConfig_Color_ColorSpace {
	if m != nil && m.ColorSpace != nil {
		return *m.ColorSpace
	}
	return Default_ConvoxLightConfig_Color_ColorSpace
}

func (m *ConvoxLightConfig_Color) GetCoordinates() []uint32 {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func init() {
	proto.RegisterEnum("org.convox.lights.ConvoxLightConfig_Color_ColorSpace", ConvoxLightConfig_Color_ColorSpace_name, ConvoxLightConfig_Color_ColorSpace_value)
}
